# Generated by Django 4.1.7 on 2023-05-18 20:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('djangocopy', '0010_historicalnavbar_anonymous_navbar_anonymous_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('url', models.URLField()),
                ('status_code', models.IntegerField()),
                ('ip', models.GenericIPAddressField()),
                ('referrer', models.URLField()),
                ('user_agent', models.TextField()),
                ('session', models.CharField(max_length=40)),
                ('device_info', models.TextField()),
                ('language', models.CharField(max_length=5)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
