# Generated by Django 4.2.1 on 2023-05-19 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocopy', '0011_pagevisit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagevisit',
            name='session',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
