# Generated by Django 4.2.1 on 2023-07-29 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocopy', '0012_alter_pagevisit_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='__get_image_upload_path__'),
        ),
        migrations.AlterField(
            model_name='template',
            name='template',
            field=models.FileField(upload_to=''),
        ),
    ]
