# Generated by Django 4.2.7 on 2023-12-03 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangocopy', '0013_alter_image_image_alter_template_template'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalnavbar',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalnavbar',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='historicalpage',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalpage',
            name='template',
        ),
        migrations.DeleteModel(
            name='HistoricalCopy',
        ),
        migrations.DeleteModel(
            name='HistoricalNavbar',
        ),
        migrations.DeleteModel(
            name='HistoricalPage',
        ),
    ]
